stores:
  - id: lidl
    name: Lidl
  - id: aldi
    name: Aldi
  - id: jumbo
    name: Jumbo
  - id: albert_heijn
    name: Albert Heijn
  - id: hoogvliet
    name: Hoogvliet
  - id: makro
    name: Makro
    business_only: true
